apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b3p3xsegv-go 
  janus-idp.io/tekton: b3p3xsegv-go
  backstage.io/kubernetes-id: b3p3xsegv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b3p3xsegv-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml